// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/fliq.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


                /// Main entrypoint of the Rust API
                class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
                  @internal
                  static final instance = RustLib._();

                  RustLib._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustLibApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required RustLibApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

                  @override
                  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    await api.crateApiFliqInitApp();

                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.11.1';

                  @override
                  int get rustContentHash => 157708142;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'rust_lib_fliq',
                    ioDirectory: 'rust/target/release/',
                    webPrefix: 'pkg/',
                  );
                }
                

                abstract class RustLibApi extends BaseApi {
                  void crateApiFliqFliqSessionCancel({required FliqSession that });

void crateApiFliqFliqSessionDecide({required FliqSession that , required bool accept });

Stream<FliqEvent> crateApiFliqFliqSessionHost({required FliqSession that , required Settings settings , required List<String> files });

Stream<FliqEvent> crateApiFliqFliqSessionJoin({required FliqSession that , required Settings settings , required String code , required List<String> files });

FliqSession crateApiFliqFliqSessionNew();

EngineFacts crateApiFliqEngineFacts({required Settings settings });

Future<EventKind> crateApiFliqEventKindDefault();

Future<FliqEvent> crateApiFliqFliqEventDefault();

Future<FolderInfo> crateApiFliqFolderInfo({required String path });

Future<void> crateApiFliqInitApp();

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_FliqSession;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_FliqSession;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_FliqSessionPtr;


                }
                

                class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
                  RustLibApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override void crateApiFliqFliqSessionCancel({required FliqSession that })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession(that, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiFliqFliqSessionCancelConstMeta,
            argValues: [that],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFliqFliqSessionCancelConstMeta => const TaskConstMeta(
            debugName: "FliqSession_cancel",
            argNames: ["that"],
        );
        

@override void crateApiFliqFliqSessionDecide({required FliqSession that , required bool accept })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession(that, serializer);
sse_encode_bool(accept, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiFliqFliqSessionDecideConstMeta,
            argValues: [that, accept],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFliqFliqSessionDecideConstMeta => const TaskConstMeta(
            debugName: "FliqSession_decide",
            argNames: ["that", "accept"],
        );
        

@override Stream<FliqEvent> crateApiFliqFliqSessionHost({required FliqSession that , required Settings settings , required List<String> files })  { 
            final sink = RustStreamSink<FliqEvent>();
            unawaited(handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession(that, serializer);
sse_encode_box_autoadd_settings(settings, serializer);
sse_encode_list_String(files, serializer);
sse_encode_StreamSink_fliq_event_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateApiFliqFliqSessionHostConstMeta,
            argValues: [that, settings, files, sink],
            apiImpl: this,
        )));
            return sink.stream;
             }


        TaskConstMeta get kCrateApiFliqFliqSessionHostConstMeta => const TaskConstMeta(
            debugName: "FliqSession_host",
            argNames: ["that", "settings", "files", "sink"],
        );
        

@override Stream<FliqEvent> crateApiFliqFliqSessionJoin({required FliqSession that , required Settings settings , required String code , required List<String> files })  { 
            final sink = RustStreamSink<FliqEvent>();
            unawaited(handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession(that, serializer);
sse_encode_box_autoadd_settings(settings, serializer);
sse_encode_String(code, serializer);
sse_encode_list_String(files, serializer);
sse_encode_StreamSink_fliq_event_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateApiFliqFliqSessionJoinConstMeta,
            argValues: [that, settings, code, files, sink],
            apiImpl: this,
        )));
            return sink.stream;
             }


        TaskConstMeta get kCrateApiFliqFliqSessionJoinConstMeta => const TaskConstMeta(
            debugName: "FliqSession_join",
            argNames: ["that", "settings", "code", "files", "sink"],
        );
        

@override FliqSession crateApiFliqFliqSessionNew()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiFliqFliqSessionNewConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFliqFliqSessionNewConstMeta => const TaskConstMeta(
            debugName: "FliqSession_new",
            argNames: [],
        );
        

@override EngineFacts crateApiFliqEngineFacts({required Settings settings })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_box_autoadd_settings(settings, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_engine_facts,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiFliqEngineFactsConstMeta,
            argValues: [settings],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFliqEngineFactsConstMeta => const TaskConstMeta(
            debugName: "engine_facts",
            argNames: ["settings"],
        );
        

@override Future<EventKind> crateApiFliqEventKindDefault()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_event_kind,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiFliqEventKindDefaultConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFliqEventKindDefaultConstMeta => const TaskConstMeta(
            debugName: "event_kind_default",
            argNames: [],
        );
        

@override Future<FliqEvent> crateApiFliqFliqEventDefault()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_fliq_event,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiFliqFliqEventDefaultConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFliqFliqEventDefaultConstMeta => const TaskConstMeta(
            debugName: "fliq_event_default",
            argNames: [],
        );
        

@override Future<FolderInfo> crateApiFliqFolderInfo({required String path })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(path, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_folder_info,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateApiFliqFolderInfoConstMeta,
            argValues: [path],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFliqFolderInfoConstMeta => const TaskConstMeta(
            debugName: "folder_info",
            argNames: ["path"],
        );
        

@override Future<void> crateApiFliqInitApp()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiFliqInitAppConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFliqInitAppConstMeta => const TaskConstMeta(
            debugName: "init_app",
            argNames: [],
        );
        

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_FliqSession => wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_FliqSession => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession;



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return AnyhowException(raw as String); }

@protected FliqSession dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return FliqSessionImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected FliqSession dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return FliqSessionImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected FliqSession dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return FliqSessionImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected RustStreamSink<FliqEvent> dco_decode_StreamSink_fliq_event_Sse(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
throw UnimplementedError(); }

@protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected bool dco_decode_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as bool; }

@protected double dco_decode_box_autoadd_f_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as double; }

@protected Settings dco_decode_box_autoadd_settings(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_settings(raw); }

@protected EngineFacts dco_decode_engine_facts(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return EngineFacts(maxPayloadBytes: dco_decode_i_64(arr[0]),
cryptoLabel: dco_decode_String(arr[1]),
cipher: dco_decode_String(arr[2]),
inflightBudgetBytes: dco_decode_i_64(arr[3]),); }

@protected EventKind dco_decode_event_kind(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return EventKind.values[raw as int]; }

@protected double dco_decode_f_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as double; }

@protected FileEntry dco_decode_file_entry(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
                return FileEntry(name: dco_decode_String(arr[0]),
size: dco_decode_i_64(arr[1]),
path: dco_decode_opt_String(arr[2]),); }

@protected FliqEvent dco_decode_fliq_event(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 23) throw Exception('unexpected arr length: expect 23 but see ${arr.length}');
                return FliqEvent(kind: dco_decode_event_kind(arr[0]),
uri: dco_decode_String(arr[1]),
addresses: dco_decode_list_String(arr[2]),
unreachable: dco_decode_list_String(arr[3]),
port: dco_decode_u_16(arr[4]),
expiresUnix: dco_decode_i_64(arr[5]),
code: dco_decode_String(arr[6]),
peerName: dco_decode_String(arr[7]),
files: dco_decode_list_file_entry(arr[8]),
total: dco_decode_i_64(arr[9]),
done: dco_decode_i_64(arr[10]),
freeSpace: dco_decode_i_64(arr[11]),
fat32Warning: dco_decode_bool(arr[12]),
moveSources: dco_decode_bool(arr[13]),
mbps: dco_decode_f_64(arr[14]),
etaSecs: dco_decode_opt_box_autoadd_f_64(arr[15]),
secs: dco_decode_f_64(arr[16]),
streams: dco_decode_u_16(arr[17]),
bottleneck: dco_decode_String(arr[18]),
index: dco_decode_u_32(arr[19]),
name: dco_decode_String(arr[20]),
errorCode: dco_decode_String(arr[21]),
message: dco_decode_String(arr[22]),); }

@protected FolderInfo dco_decode_folder_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
                return FolderInfo(freeBytes: dco_decode_i_64(arr[0]),
isFat: dco_decode_bool(arr[1]),); }

@protected int dco_decode_i_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected PlatformInt64 dco_decode_i_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeI64(raw); }

@protected List<String> dco_decode_list_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_String).toList(); }

@protected List<FileEntry> dco_decode_list_file_entry(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_file_entry).toList(); }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected String? dco_decode_opt_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_String(raw); }

@protected double? dco_decode_opt_box_autoadd_f_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_box_autoadd_f_64(raw); }

@protected Settings dco_decode_settings(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return Settings(deviceName: dco_decode_String(arr[0]),
saveDir: dco_decode_String(arr[1]),
maxTotalBytes: dco_decode_i_64(arr[2]),
moveSources: dco_decode_bool(arr[3]),); }

@protected int dco_decode_u_16(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected int dco_decode_u_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected BigInt dco_decode_usize(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeU64(raw); }

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_String(deserializer);
        return AnyhowException(inner); }

@protected FliqSession sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return FliqSessionImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected FliqSession sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return FliqSessionImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected FliqSession sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return FliqSessionImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected RustStreamSink<FliqEvent> sse_decode_StreamSink_fliq_event_Sse(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
throw UnimplementedError('Unreachable ()'); }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected double sse_decode_box_autoadd_f_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_f_64(deserializer)); }

@protected Settings sse_decode_box_autoadd_settings(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_settings(deserializer)); }

@protected EngineFacts sse_decode_engine_facts(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_maxPayloadBytes = sse_decode_i_64(deserializer);
var var_cryptoLabel = sse_decode_String(deserializer);
var var_cipher = sse_decode_String(deserializer);
var var_inflightBudgetBytes = sse_decode_i_64(deserializer);
return EngineFacts(maxPayloadBytes: var_maxPayloadBytes, cryptoLabel: var_cryptoLabel, cipher: var_cipher, inflightBudgetBytes: var_inflightBudgetBytes); }

@protected EventKind sse_decode_event_kind(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return EventKind.values[inner]; }

@protected double sse_decode_f_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getFloat64(); }

@protected FileEntry sse_decode_file_entry(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_name = sse_decode_String(deserializer);
var var_size = sse_decode_i_64(deserializer);
var var_path = sse_decode_opt_String(deserializer);
return FileEntry(name: var_name, size: var_size, path: var_path); }

@protected FliqEvent sse_decode_fliq_event(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_kind = sse_decode_event_kind(deserializer);
var var_uri = sse_decode_String(deserializer);
var var_addresses = sse_decode_list_String(deserializer);
var var_unreachable = sse_decode_list_String(deserializer);
var var_port = sse_decode_u_16(deserializer);
var var_expiresUnix = sse_decode_i_64(deserializer);
var var_code = sse_decode_String(deserializer);
var var_peerName = sse_decode_String(deserializer);
var var_files = sse_decode_list_file_entry(deserializer);
var var_total = sse_decode_i_64(deserializer);
var var_done = sse_decode_i_64(deserializer);
var var_freeSpace = sse_decode_i_64(deserializer);
var var_fat32Warning = sse_decode_bool(deserializer);
var var_moveSources = sse_decode_bool(deserializer);
var var_mbps = sse_decode_f_64(deserializer);
var var_etaSecs = sse_decode_opt_box_autoadd_f_64(deserializer);
var var_secs = sse_decode_f_64(deserializer);
var var_streams = sse_decode_u_16(deserializer);
var var_bottleneck = sse_decode_String(deserializer);
var var_index = sse_decode_u_32(deserializer);
var var_name = sse_decode_String(deserializer);
var var_errorCode = sse_decode_String(deserializer);
var var_message = sse_decode_String(deserializer);
return FliqEvent(kind: var_kind, uri: var_uri, addresses: var_addresses, unreachable: var_unreachable, port: var_port, expiresUnix: var_expiresUnix, code: var_code, peerName: var_peerName, files: var_files, total: var_total, done: var_done, freeSpace: var_freeSpace, fat32Warning: var_fat32Warning, moveSources: var_moveSources, mbps: var_mbps, etaSecs: var_etaSecs, secs: var_secs, streams: var_streams, bottleneck: var_bottleneck, index: var_index, name: var_name, errorCode: var_errorCode, message: var_message); }

@protected FolderInfo sse_decode_folder_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_freeBytes = sse_decode_i_64(deserializer);
var var_isFat = sse_decode_bool(deserializer);
return FolderInfo(freeBytes: var_freeBytes, isFat: var_isFat); }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected PlatformInt64 sse_decode_i_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getPlatformInt64(); }

@protected List<String> sse_decode_list_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <String>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_String(deserializer)); }
        return ans_;
         }

@protected List<FileEntry> sse_decode_list_file_entry(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <FileEntry>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_file_entry(deserializer)); }
        return ans_;
         }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected String? sse_decode_opt_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_String(deserializer));
            } else {
                return null;
            }
             }

@protected double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_box_autoadd_f_64(deserializer));
            } else {
                return null;
            }
             }

@protected Settings sse_decode_settings(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_deviceName = sse_decode_String(deserializer);
var var_saveDir = sse_decode_String(deserializer);
var var_maxTotalBytes = sse_decode_i_64(deserializer);
var var_moveSources = sse_decode_bool(deserializer);
return Settings(deviceName: var_deviceName, saveDir: var_saveDir, maxTotalBytes: var_maxTotalBytes, moveSources: var_moveSources); }

@protected int sse_decode_u_16(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint16(); }

@protected int sse_decode_u_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint32(); }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected BigInt sse_decode_usize(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getBigUint64(); }

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.message, serializer); }

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession(FliqSession self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as FliqSessionImpl).frbInternalSseEncode(move: true), serializer); }

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession(FliqSession self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as FliqSessionImpl).frbInternalSseEncode(move: false), serializer); }

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFliqSession(FliqSession self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as FliqSessionImpl).frbInternalSseEncode(move: null), serializer); }

@protected void sse_encode_StreamSink_fliq_event_Sse(RustStreamSink<FliqEvent> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.setupAndSerialize(codec: SseCodec(
            decodeSuccessData: sse_decode_fliq_event,
            decodeErrorData: sse_decode_AnyhowException,
        )), serializer); }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }

@protected void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_f_64(self, serializer); }

@protected void sse_encode_box_autoadd_settings(Settings self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_settings(self, serializer); }

@protected void sse_encode_engine_facts(EngineFacts self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_64(self.maxPayloadBytes, serializer);
sse_encode_String(self.cryptoLabel, serializer);
sse_encode_String(self.cipher, serializer);
sse_encode_i_64(self.inflightBudgetBytes, serializer);
 }

@protected void sse_encode_event_kind(EventKind self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_f_64(double self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putFloat64(self); }

@protected void sse_encode_file_entry(FileEntry self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.name, serializer);
sse_encode_i_64(self.size, serializer);
sse_encode_opt_String(self.path, serializer);
 }

@protected void sse_encode_fliq_event(FliqEvent self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_event_kind(self.kind, serializer);
sse_encode_String(self.uri, serializer);
sse_encode_list_String(self.addresses, serializer);
sse_encode_list_String(self.unreachable, serializer);
sse_encode_u_16(self.port, serializer);
sse_encode_i_64(self.expiresUnix, serializer);
sse_encode_String(self.code, serializer);
sse_encode_String(self.peerName, serializer);
sse_encode_list_file_entry(self.files, serializer);
sse_encode_i_64(self.total, serializer);
sse_encode_i_64(self.done, serializer);
sse_encode_i_64(self.freeSpace, serializer);
sse_encode_bool(self.fat32Warning, serializer);
sse_encode_bool(self.moveSources, serializer);
sse_encode_f_64(self.mbps, serializer);
sse_encode_opt_box_autoadd_f_64(self.etaSecs, serializer);
sse_encode_f_64(self.secs, serializer);
sse_encode_u_16(self.streams, serializer);
sse_encode_String(self.bottleneck, serializer);
sse_encode_u_32(self.index, serializer);
sse_encode_String(self.name, serializer);
sse_encode_String(self.errorCode, serializer);
sse_encode_String(self.message, serializer);
 }

@protected void sse_encode_folder_info(FolderInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_64(self.freeBytes, serializer);
sse_encode_bool(self.isFat, serializer);
 }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }

@protected void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putPlatformInt64(self); }

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_String(item, serializer); } }

@protected void sse_encode_list_file_entry(List<FileEntry> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_file_entry(item, serializer); } }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_opt_String(String? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_String(self, serializer);
                }
                 }

@protected void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_box_autoadd_f_64(self, serializer);
                }
                 }

@protected void sse_encode_settings(Settings self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.deviceName, serializer);
sse_encode_String(self.saveDir, serializer);
sse_encode_i_64(self.maxTotalBytes, serializer);
sse_encode_bool(self.moveSources, serializer);
 }

@protected void sse_encode_u_16(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint16(self); }

@protected void sse_encode_u_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint32(self); }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_usize(BigInt self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putBigUint64(self); }
                }
                

            @sealed class FliqSessionImpl extends RustOpaque implements FliqSession {
                // Not to be used by end users
                FliqSessionImpl.frbInternalDcoDecode(List<dynamic> wire):
                    super.frbInternalDcoDecode(wire, _kStaticData);

                // Not to be used by end users
                FliqSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative):
                    super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

                static final _kStaticData = RustArcStaticData(
                    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_FliqSession,
                    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_FliqSession,
                    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_FliqSessionPtr,
                );

                 void  cancel()=>RustLib.instance.api.crateApiFliqFliqSessionCancel(that: this, );


 void  decide({required bool accept })=>RustLib.instance.api.crateApiFliqFliqSessionDecide(that: this, accept: accept);


/// Show a QR. Empty `files` = receive into the save folder; otherwise send them.
 Stream<FliqEvent>  host({required Settings settings , required List<String> files })=>RustLib.instance.api.crateApiFliqFliqSessionHost(that: this, settings: settings, files: files);


/// Use a code from the other device. `files` are sent if the other device receives.
 Stream<FliqEvent>  join({required Settings settings , required String code , required List<String> files })=>RustLib.instance.api.crateApiFliqFliqSessionJoin(that: this, settings: settings, code: code, files: files);


            }