// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `config`, `entries`, `sink_fn`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`


            EngineFacts  engineFacts({required Settings settings }) => RustLib.instance.api.crateApiFliqEngineFacts(settings: settings);

Future<FolderInfo>  folderInfo({required String path }) => RustLib.instance.api.crateApiFliqFolderInfo(path: path);

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FliqSession>>
                abstract class FliqSession implements RustOpaqueInterface {
                     void  cancel();


 void  decide({required bool accept });


/// Show a QR. Empty `files` = receive into the save folder; otherwise send them.
 Stream<FliqEvent>  host({required Settings settings , required List<String> files });


/// Use a code from the other device. `files` are sent if the other device receives.
 Stream<FliqEvent>  join({required Settings settings , required String code , required List<String> files });


factory FliqSession()=>RustLib.instance.api.crateApiFliqFliqSessionNew();



                    
                }
                

/// Values for the dashboard metrics strip (spec 10.9).
class EngineFacts  {
                final PlatformInt64 maxPayloadBytes;
final String cryptoLabel;
final String cipher;
final PlatformInt64 inflightBudgetBytes;

                const EngineFacts({required this.maxPayloadBytes ,required this.cryptoLabel ,required this.cipher ,required this.inflightBudgetBytes ,});

                
                

                
        @override
        int get hashCode => maxPayloadBytes.hashCode^cryptoLabel.hashCode^cipher.hashCode^inflightBudgetBytes.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is EngineFacts &&
                runtimeType == other.runtimeType
                && maxPayloadBytes == other.maxPayloadBytes&& cryptoLabel == other.cryptoLabel&& cipher == other.cipher&& inflightBudgetBytes == other.inflightBudgetBytes;
        
            }

/// Which event this is. A flat struct + plain enum keeps the Dart side free of code
/// generators beyond flutter_rust_bridge itself (rich enums would need `freezed`).
enum EventKind {
                    /// uri, addresses, port, expires_unix
showQr,
/// addresses (reachable), unreachable
selfCheck,
/// code, peer_name
connected,
/// code, peer_name, files, total, free_space, fat32_warning — call `decide`
offerReceived,
/// files, total, move_sources
sending,
/// done, total, mbps, eta_secs, streams, bottleneck
progress,
reconnecting,
reconnected,
/// index, name
fileVerified,
/// name
moveFailed,
/// done (= bytes), secs, mbps, files (with paths on the receiver), streams
finished,
/// error_code, message
failed,
                    ;
                    static Future<EventKind>  default_()=>RustLib.instance.api.crateApiFliqEventKindDefault();


                }

class FileEntry  {
                final String name;
final PlatformInt64 size;
final String? path;

                const FileEntry({required this.name ,required this.size ,this.path ,});

                
                

                
        @override
        int get hashCode => name.hashCode^size.hashCode^path.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is FileEntry &&
                runtimeType == other.runtimeType
                && name == other.name&& size == other.size&& path == other.path;
        
            }

class FliqEvent  {
                final EventKind kind;
final String uri;
final List<String> addresses;
final List<String> unreachable;
final int port;
final PlatformInt64 expiresUnix;
final String code;
final String peerName;
final List<FileEntry> files;
final PlatformInt64 total;
final PlatformInt64 done;
final PlatformInt64 freeSpace;
final bool fat32Warning;
final bool moveSources;
final double mbps;
final double? etaSecs;
final double secs;
final int streams;
final String bottleneck;
final int index;
final String name;
final String errorCode;
final String message;

                const FliqEvent({required this.kind ,required this.uri ,required this.addresses ,required this.unreachable ,required this.port ,required this.expiresUnix ,required this.code ,required this.peerName ,required this.files ,required this.total ,required this.done ,required this.freeSpace ,required this.fat32Warning ,required this.moveSources ,required this.mbps ,this.etaSecs ,required this.secs ,required this.streams ,required this.bottleneck ,required this.index ,required this.name ,required this.errorCode ,required this.message ,});

                static Future<FliqEvent>  default_()=>RustLib.instance.api.crateApiFliqFliqEventDefault();


                

                
        @override
        int get hashCode => kind.hashCode^uri.hashCode^addresses.hashCode^unreachable.hashCode^port.hashCode^expiresUnix.hashCode^code.hashCode^peerName.hashCode^files.hashCode^total.hashCode^done.hashCode^freeSpace.hashCode^fat32Warning.hashCode^moveSources.hashCode^mbps.hashCode^etaSecs.hashCode^secs.hashCode^streams.hashCode^bottleneck.hashCode^index.hashCode^name.hashCode^errorCode.hashCode^message.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is FliqEvent &&
                runtimeType == other.runtimeType
                && kind == other.kind&& uri == other.uri&& addresses == other.addresses&& unreachable == other.unreachable&& port == other.port&& expiresUnix == other.expiresUnix&& code == other.code&& peerName == other.peerName&& files == other.files&& total == other.total&& done == other.done&& freeSpace == other.freeSpace&& fat32Warning == other.fat32Warning&& moveSources == other.moveSources&& mbps == other.mbps&& etaSecs == other.etaSecs&& secs == other.secs&& streams == other.streams&& bottleneck == other.bottleneck&& index == other.index&& name == other.name&& errorCode == other.errorCode&& message == other.message;
        
            }

class FolderInfo  {
                final PlatformInt64 freeBytes;
final bool isFat;

                const FolderInfo({required this.freeBytes ,required this.isFat ,});

                
                

                
        @override
        int get hashCode => freeBytes.hashCode^isFat.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is FolderInfo &&
                runtimeType == other.runtimeType
                && freeBytes == other.freeBytes&& isFat == other.isFat;
        
            }

/// User settings the UI keeps (spec 9 item 10).
class Settings  {
                final String deviceName;
final String saveDir;
/// Configured size limit in bytes (0 = default 50 GiB).
final PlatformInt64 maxTotalBytes;
final bool moveSources;

                const Settings({required this.deviceName ,required this.saveDir ,required this.maxTotalBytes ,required this.moveSources ,});

                
                

                
        @override
        int get hashCode => deviceName.hashCode^saveDir.hashCode^maxTotalBytes.hashCode^moveSources.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is Settings &&
                runtimeType == other.runtimeType
                && deviceName == other.deviceName&& saveDir == other.saveDir&& maxTotalBytes == other.maxTotalBytes&& moveSources == other.moveSources;
        
            }
            